version: "3.7"
services:
    log4fns:
        build:
            context: .
        volumes:
            - ".:/app"
            - "/app/node_modules"
        image: log4fns:dev
        entrypoint: [ "npm", "run", "start:watch" ]
        container_name: log4fns